name: 'Jit security-controls action'
description: 'Runs a Jit security-control on a target dir'
inputs:
  target_dir:
    description: 'Directory to scan'
    required: true
  security_control:
    description: "Docker image tag path of security control to execute"
    required: true
  security_control_args:
    description: "argument to pass to the security control"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        docker run --rm -e CONFIG_FILE_PATH=/.jit/jit.yml -e GITHUB_EVENT='${{ toJSON(github) }}' -e SOURCE_CODE_FOLDER=/code -v $(pwd)/.jit:/.jit -v $(pwd)/${{ inputs.target_dir }}:/code ${{ inputs.security_control }} -- ${{ inputs.security_control_args }} > artifact.json
      shell: bash
