name: 'Jit security-controls action'
description: 'Runs a Jit security-control on a target dir'
inputs:
  docker_user:
    description: 'user for docker registry'
    required: true
  docker_password:
    description: 'password for docker registry'
    required: true
  container_args:
    description: 'container additional args'
    required: false
    default: ""
  security_control:
    description: "Docker image tag path of security control to execute"
    required: true
  security_control_args:
    description: "argument to pass to the security control"
    required: false
  security_control_output_file:
    description: "path to the security control output"
    required: false
    default: ""
  dispatch_type:
    description: "'workflow' or 'repository' (dispatch_type is deprecated and will be removed)"
    required: false
    default: "workflow"
  fail_on_findings:
    description: "fail control when finding is found"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Set centralized_repo_files_location env var
      shell: bash
      env:
        CENTRALIZED_REPO_FILES_LOCATION: ${{ fromJSON(github.event.inputs.client_payload).payload.centralized_repo_files_location || '' }}
      run: |
        echo "CONFIG_FILE_PATH=/.jit/${CENTRALIZED_REPO_FILES_LOCATION}jit.yml" >> $GITHUB_ENV
        echo "CENTRALIZED_REPO_FILES_LOCATION_PATH=${PWD}/.jit/${CENTRALIZED_REPO_FILES_LOCATION}" >> $GITHUB_ENV
    - name: Checkout centralized repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ fromJSON(github.event.inputs.client_payload).payload.github_token }}
        ref: ''
        path: ".jit/"
    - name: Checkout original repository
      uses: actions/checkout@v2
      with:
        repository: ${{ fromJSON(github.event.inputs.client_payload).payload.full_repo_path }}
        ref: ${{ fromJSON(github.event.inputs.client_payload).payload.commits.head_sha }}
        fetch-depth: 0
        token: ${{ fromJSON(github.event.inputs.client_payload).payload.github_token }}
        path: "code/"
    - name: Check out jit-github-actions
      uses: actions/checkout@v2
      with:
        repository: jitsecurity-controls/jit-github-action
        ref: main
        path: ./.github/actions/jit-github-action
    - name: Run The Action
      if: always()
      run: |
        echo "${{ inputs.docker_password }}" | base64 --decode > /tmp/token.txt
        cat /tmp/token.txt | docker login ghcr.io --username ${{ inputs.docker_user }} --password-stdin
        docker pull ${{ inputs.security_control }}
        JSON_GITHUB_EVENT='${{ toJSON(github) }}'
        B64_ENCODED_GITHUB_EVENT=$(echo $JSON_GITHUB_EVENT | base64)
        docker run --rm -e CONFIG_FILE_PATH="${CONFIG_FILE_PATH}" ${{ inputs.container_args }} -e GITHUB_EVENT="$B64_ENCODED_GITHUB_EVENT" -e SOURCE_CODE_FOLDER=/code -e SECURITY_CONTROL_OUTPUT_FILE=${{ inputs.security_control_output_file }} -v ${CENTRALIZED_REPO_FILES_LOCATION_PATH}:/.jit -e FAIL_ON_FINDINGS=${{ inputs.fail_on_findings }} -v $(pwd)/code:/code ${{ inputs.security_control }} -- ${{ inputs.security_control_args }}
      shell: bash
