name: 'Jit security-controls action'
description: 'Runs a Jit security-control on a target dir'
inputs:
  pull_key:
    description: 'key for pulling the action repo'
    required: true
  docker_user:
    description: 'user for docker registry'
    required: true
  docker_password:
    description: 'password for docker registry'
    required: true
  security_control:
    description: "Docker image tag path of security control to execute"
    required: true
  security_control_args:
    description: "argument to pass to the security control"
    required: false
  security_control_output_file:
    description: "path to the security control output"
    required: false
    default: ""
  dispatch_type:
    description: "workflow or repository (deprecated) dispatch"
    required: false
    default: "repository"

runs:
  using: "composite"
  steps:
    - name: Checkout .jit
      if: ${{ inputs.dispatch_type == 'workflow' }}
      uses: actions/checkout@v2   
      with:
        repository: ${{ github.repository }}
        token: ${{ fromJSON(github.event.inputs.client_payload).payload.github_token }}
        ref: main
        path: ".jit/"
    - name: Checkout original repository
      if: ${{ inputs.dispatch_type == 'workflow' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ fromJSON(github.event.inputs.client_payload).payload.full_repo_path }}
        ref: ${{ fromJSON(github.event.inputs.client_payload).payload.commits.head_sha }}
        fetch-depth: 0
        token: ${{ fromJSON(github.event.inputs.client_payload).payload.github_token }}
        path: "code/"
    - name: Checkout .jit (using deprecated repository)
      if: ${{ inputs.dispatch_type == 'repository' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ github.event.client_payload.payload.github_token }}
        ref: main
        path: ".jit/"
    - name: Checkout original repository (using deprecated repository)
      if: ${{ inputs.dispatch_type == 'repository' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.payload.full_repo_path }}
        ref: ${{ github.event.client_payload.payload.commits.head_sha }}
        fetch-depth: 0
        token: ${{ github.event.client_payload.payload.github_token }}
        path: "code/"
    - name: Check out jit-github-actions
      uses: actions/checkout@v2
      with:
        repository: jitsecurity-controls/jit-github-action
        ref: main
        token: ${{ inputs.pull_key }}
        path: ./.github/actions/jit-github-action
    - name: Run The Action
      if: always()
      run: |
        docker login ghcr.io --username ${{ inputs.docker_user }} --password ${{ inputs.docker_password }}
        docker pull ${{ inputs.security_control }}
        docker run --rm -e CONFIG_FILE_PATH=/.jit/jit.yml -e GITHUB_EVENT='${{ toJSON(github) }}' -e SOURCE_CODE_FOLDER=/code -e SECURITY_CONTROL_OUTPUT_FILE=${{ inputs.security_control_output_file }} -v $(pwd)/.jit:/.jit -v $(pwd)/code:/code ${{ inputs.security_control }} -- ${{ inputs.security_control_args }} > artifact.json
      shell: bash
