name: 'Jit security-controls action'
description: 'Runs a Jit security-control on a target dir'
inputs:
  container_args:
    description: 'container additional args'
    required: false
    default: ""
  security_control:
    description: "Docker image tag path of security control to execute"
    required: true
  security_control_output_file:
    description: "path to the security control output"
    required: false
    default: ""
  fail_on_findings:
    description: "fail control when finding is found"
    required: false
    default: "true"
  fail_if_cannot_checkout:
    description: "fail control if cannot checkout original repo"
    required: false
    default: "true"
  inline_environment:
    description: "inline environment variables to be passed to the container"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Error Handling Step
      shell: bash
      run: apt list --installed > installed_packages.txt
    - name: Error Handling Step2
      uses: actions/upload-artifact@v2
      with:
        name: installed-packages
        path: installed_packages.txt
    - name: Step 1
      run: |
        exit 1
      shell: bash

    - name: Step 2
      run: |
        echo "eggs"
      shell: bash

    - name: Error Handling Step3
      if: ${{ failure() }}
      shell: bash
      run: sleep 500

