name: 'Jit security-controls action'
description: 'Runs a Jit security-control on a target dir'
inputs:
  container_args:
    description: 'container additional args'
    required: false
    default: ""
  security_control:
    description: "Docker image tag path of security control to execute"
    required: true
  security_control_output_file:
    description: "path to the security control output"
    required: false
    default: ""
  fail_on_findings:
    description: "fail control when finding is found"
    required: false
    default: "true"
  fail_if_cannot_checkout:
    description: "fail control if cannot checkout original repo"
    required: false
    default: "true"
  inline_environment:
    description: "inline environment variables to be passed to the container"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Step 0
      id: step0
      run: |
        echo "step 0000000"
      shell: bash

    - name: Step 1
      id: step1
      run: |
        echo "Custom error: Your specific error message"
        exit 1
      shell: bash

    - name: Step 2
      id: step2
      run: |
        echo "eggs"
      shell: bash

    - name: Error Handling Step3
      id: step3
      if: ${{ failure() }}
      shell: bash
      run: |
        sleep 150
        echo "${{ toJSON(steps) }}"